# -*- coding: utf-8 -*-
"""Final Project Quality Control / Aggregation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZYecuW6iNQ0vRC6Bzt-zAhrIFnj7BK4P
"""

import pandas as pd
import csv

def majority_vote(mturk_res):
    attributes = mturk_res['Input.attr_id'].tolist()
    adj1 = list(zip(attributes,(mturk_res['Input.adj_1'].tolist()),(mturk_res['Answer.adj_1'].tolist()), (mturk_res['Input.adj_2'].tolist()),(mturk_res['Answer.adj_2'].tolist()), (mturk_res['Input.adj_3'].tolist()),(mturk_res['Answer.adj_3'].tolist()), (mturk_res['Input.adj_4'].tolist()),(mturk_res['Answer.adj_4'].tolist()), (mturk_res['Input.adj_5'].tolist()),(mturk_res['Answer.adj_5'].tolist()), (mturk_res['Input.adj_6'].tolist()),(mturk_res['Answer.adj_6'].tolist()), (mturk_res['Input.adj_7'].tolist()),(mturk_res['Answer.adj_7'].tolist()), (mturk_res['Input.adj_8'].tolist()),(mturk_res['Answer.adj_8'].tolist()), (mturk_res['Input.adj_9'].tolist()),(mturk_res['Answer.adj_9'].tolist()), (mturk_res['Input.adj_10'].tolist()),(mturk_res['Answer.adj_10'].tolist()) ))
    
    l = len(adj1)
    dict = {}
    for i in range(l):
      for j in range(1,len(adj1[0]),2):
        curPair = (adj1[i][0], adj1[i][j])
        curLab = 1 if (adj1[i][j+1] == 'Yes') else -1
        if (curPair in dict):
          dict[curPair] = dict[curPair] + curLab
        else:
          dict[curPair] = curLab
    ans = []

    for pair in dict.keys():
      (attr, adj) = pair
      
      tot = dict[pair]
      label = tot >= 0
      ans.append((attr, adj, label))
    
    ans.sort(key=lambda tup: (tup[0], tup[1]))
    print(ans)
    return ans


def select_qualified_worker(mturk_res_hit2):
    WIds = mturk_res_hit2['worker_id'].tolist()
    QCs = list(zip(WIds,(mturk_res_hit2['Answer.neg_qual_ctrl'].tolist()), (mturk_res_hit2['Answer.pos_qual_ctrl'].tolist())))
    WorkerTots = {}
    WorkerCounts = {}
    
    for i in range(len(QCs)):
      #print("outer")
      worker = QCs[i][0]
      negativeCorrect = False
      numPosCorrect = 0
      
      if (worker in WorkerCounts):
        WorkerCounts[worker] += 1
      else:
        WorkerCounts[worker] = 1

      for j in range(1,len(QCs[1])):

        correct = QCs[i][j] == 'Yes'

        isNan = QCs[i][j] != 'Yes' and QCs[i][j] != 'No' and QCs[i][j] != 'Naa'
        if (j == 1 and not isNan): 
          negativeCorrect = QCs[i][j] != 'Yes'
        if correct and j != 1:
          numPosCorrect += 1
      passed = negativeCorrect and numPosCorrect >= 1
      toAdd = 1 if passed else 0  
      if worker in WorkerTots:
        numPassed = WorkerTots[worker]
        WorkerTots[worker] = numPassed + toAdd
      else:
        WorkerTots[worker] = toAdd

    WIds.sort()
    ans = []
    for w in WIds:
      numPassed = WorkerTots[w]
      numHits = WorkerCounts[w]
      percentage = numPassed/numHits
      if (percentage >= 0.66 and numHits >= 1):
        ans.append((w, round(percentage,3)))

    return ans

def select_coherent_sentences(mturk_res_hit2, sqw):
    print(sqw)
    WIds = mturk_res_hit2['worker_id'].tolist()
    QCs = list(zip(WIds,(mturk_res_hit2['Input.lyric_1'].tolist()), (mturk_res_hit2['Answer.lyric_1'].tolist()) , (mturk_res_hit2['Input.lyric_2'].tolist()), (mturk_res_hit2['Answer.lyric_2'].tolist()) , (mturk_res_hit2['Input.lyric_3'].tolist()), (mturk_res_hit2['Answer.lyric_3'].tolist()), (mturk_res_hit2['Input.lyric_4'].tolist()) , (mturk_res_hit2['Answer.lyric_4'].tolist())))
    ans = []

    for i in range(len(QCs)):
      #print("outer")
      worker = QCs[i][0]
      if [item for item in sqw if item[0] == worker] :
        for j in range(1,len(QCs[1]), 2):
          if QCs[i][j+1] == 'Yes':
            ans.append(QCs[i][j])

    print(ans)
    return ans

def main():
    # Read in CVS result file with pandas
    # PLEASE DO NOT CHANGE
    mturk_res_hit2 = pd.read_csv('Final_project_data_second_Hit.csv')

    sqw = select_qualified_worker(mturk_res_hit2)
    with open('QC_Workers','w') as out:
      csv_out=csv.writer(out)
      csv_out.writerow(['worker_id', 'percentage'])
      csv_out.writerows(sqw)

    cs = select_coherent_sentences(mturk_res_hit2, sqw)
    df = pd.DataFrame(cs)
    df.to_csv('CoherentTurkerLyrics.csv', index=False)

if __name__ == '__main__':
    main()